### ISSUE TITLE
[Bundle mainBundle] return null

### ISSUE THREAD

**Issue by xurxodev** [klaaspieter/configuration#1]
Hi

I downloaded your project and work fine but if I create a new project and without doing anything, I write NSBundle *bundle = [NSBundle mainBundle] in AppDelegate and this return bundle properly in debug mode but return nil in release mode.

I set release mode change build configuration in run section from scheme.

You are doing additional configuration for work it properly?

thanks

**Comment by klaaspieter** [comment]
Can you email me your project? 
klaaspieter@annema.me

Thanks.

**Comment by xurxodev** [comment]
Hi Klasspieter

I've found the problem, in release mode every log prints to nil but work
properly.

I'm a Net developer and in Visual Studio this work different.

Thanks

2015-01-27 20:07 GMT+01:00 Klaas Pieter Annema notifications@github.com:

**Comment by klaaspieter** [comment]
Ok. Thanks.
